version: "3.8"

services:
  app:
    image: php:7.4-cli-alpine3.13
    ports:
      - "8000:8000"
    volumes:
      - ./app/:/var/www/html/app/
    working_dir: /var/www/html/app/
    # command: ["php", "-S", "0.0.0.0:8000", "index.php"]
    tty: true
